### ISSUE TITLE
Calisphere - AL2023 & python3.9 upgrades

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/public_interface#320]
python 3.8 end of life October 2024 - Upgrade python version - https://devguide.python.org/versions/

We'll need to upgrade python versions in the following instances:
- ~calisphere-stage beanstalk~
- ~calisphere beanstalk~
- registry-stg ec2
- registry-prd ec2

And in the following codebases:
- ~public_interface~
- ~exhibitapp~
- avram

**Comment by bibliotechy** [comment]
Can this be rolled up into [Calisphere beanstalk migration](https://github.com/ucldc/rikolti/issues/859) ?

**Comment by amywieliczka** [comment]
https://github.com/cdlib/pad-rikolti-deploy/pull/10
https://github.com/ucldc/public_interface/pull/407

...still working on registry, but I'm going to punt on the AL2023 upgrade and just do the python version upgrade to 3.9 for registry.

**Comment by amywieliczka** [comment]
Nevermind! There is no Python 3.9 available for Amazon Linux 2, so I'm going to go ahead and bundle the AL2023 upgrade and the Python 3.9 version upgrade. @bibliotechy and I discussed doing this in early November, despite Python 3.8's end of life on Oct 31st.
