### ISSUE TITLE
[bug] Link to the source contributor record doesn't include "type" in the sentence structure (externally-harvested)

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#327]
On the link that shows below the item record thumbnail, we:
- Expect: "View source image on the..." or "Read item on..."
- Actual: "View source on the..."

Likely a type issue, possibly UI, possibly harvesting.

See examples:
- Image: https://calisphere-stage.cdlib.org/item/ark:/13030/tf0b69n42z/ vs https://calisphere.org/item/ark:/13030/tf0b69n42z/
- Text: https://calisphere-stage.cdlib.org/item/5cb6babd06a64701f4e578998ea8490d/ vs https://calisphere.org/item/5cb6babd06a64701f4e578998ea8490d/
- Video: https://calisphere-stage.cdlib.org/item/cbe6c64eca4dcaf013500eeea418a3c0/
- Audio: https://calisphere-stage.cdlib.org/item/d88c4057b1279a66c4b356f2a6131cc3/

**Comment by amywieliczka** [comment]
This is a Calisphere UI issue; resolved in https://github.com/ucldc/public_interface/pull/326

**Comment by barbarahui** [comment]
The fix for this is deployed to test- and stage-.

**Comment by christinklez** [comment]
@aturner this looks great on -stage!
