### ISSUE TITLE
[bug] Empty type icon placeholders appearing on externally-harvested (& ETL'd) item record pages

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#328]
See examples:

- image: https://calisphere-stage.cdlib.org/item/e59f5fcd170fdbf48168807b63c7c566/
- video: https://calisphere-stage.cdlib.org/item/cbe6c64eca4dcaf013500eeea418a3c0/
- text: https://calisphere-stage.cdlib.org/item/ark:/20775/bb6496315b/
- audio: https://calisphere-stage.cdlib.org/item/d88c4057b1279a66c4b356f2a6131cc3/

**Comment by amywieliczka** [comment]
This issue is a Calisphere UI issue, resolved in #326

**Comment by barbarahui** [comment]
The fix for this is deployed to test- and stage-.

**Comment by christinklez** [comment]
@aturner this looks great on -stage!

**Comment by christinklez** [comment]
@barbarahui this issue looks to be appearing still, on certain objects:
https://calisphere-stage.cdlib.org/item/8877fed05bb01eae5b750562d9d66e04/

**Comment by christinklez** [comment]
And this collection of videos is missing the icon: https://calisphere-stage.cdlib.org/collections/26311/

**Comment by christinklez** [comment]
This latest issue is possibly related to #895 (t e x i m a g) issue.

**Comment by christinklez** [comment]
Closing this as fixed via #895!
