### ISSUE TITLE
[to do] frontend updates to label empty "type" & empty "date" values

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#350]
This collection has 92 objects that have an empty "type" field:
- Collection landing page: https://calisphere-stage.cdlib.org/collections/6406/
- Collection landing page with the empty facet selected: https://calisphere-stage.cdlib.org/collections/6406/?q=&sort=a&type_ss=

This is a Nuxeo collection with 5 objects with an empty "type" field:
- Collection landing page: https://calisphere-stage.cdlib.org/collections/27116/
- Collection landing page with the empty facet selected: https://calisphere-stage.cdlib.org/collections/27116/?q=&sort=a&type_ss=

When you do a sitewide empty search, the frontend is still confused: https://calisphere-stage.cdlib.org/search/?q=

What are our options here?

Ideally, the records do continue to publish through to Calisphere, and perhaps:
- option 1: These records appear in the search results, but don't get listed on the "type" facets (which is how Calisphere currently handles in the frontend)
- option 2: These records assign an `unknown` type value? And instead of the blanks, they can be selected by type `unknown`
- other options?

**Comment by amywieliczka** [comment]
Dev work on this is complete with #351 but I still need some proper language approvals.

**Comment by christinklez** [comment]
Thanks @amywieliczka! I see the new "date value not supplied" and "type value not supplied" labels--they both look great, and the functionality of the search/browse pages also look good.

@aturner--let's plan to touch base to discuss the labels. Thanks!

**Comment by christinklez** [comment]
Closing this work as done! The issue initially reported (frontend being confused by empty values) is resolved, and the dev work to prep to transform the blank values with labels looks good.

Opened a new issue to formalize the label, see #959.

Thanks!
