### ISSUE TITLE
[low priority question] Records that couldn't be thumbnailed AND have type `None` have empty grey tiles. Explore options for an `icon of last resort`?

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#355]
Here's an example of a record that couldn't be thumbnailed (grey tile with a white circle in the middle)
https://calisphere-stage.cdlib.org/item/ark:/21198/zz0025pngj/

And here's how it looks in a search result (appears as a grey tile)
https://calisphere-stage.cdlib.org/collections/28111/?rq=Ethel%20Sissle%2C%20Catherine%20Garcia%20and%20Marva%20Louis%2C%20Los%20Angeles%2C%201940s
Note: These used to display as broken-image icons, because a thumbnail did not get fished (or there was not an image to be thumbnailed.)

**A low priority question: Are there options to include last resort type icons here?**
Perhaps something like this? https://calisphere-stage.cdlib.org/collections/194/?q=&sort=a&rq=ark%3A%2F81235%2Fd80n8h

(Side note: Since the lack of a `type` data value is typically originating on the data provider end, we should report these to contributors.)

Older pivotal issue, perhaps related: https://www.pivotaltracker.com/n/projects/935010/stories/154824496

**Comment by amywieliczka** [comment]
Resolved here: https://github.com/ucldc/public_interface/pull/354 and https://github.com/ucldc/exhibitapp/pull/40

**Comment by amywieliczka** [comment]
@christinklez this is deployed to calisphere-stage

**Comment by christinklez** [comment]
Thanks @amywieliczka! This looks great on -stage.

CC @aturner as an FYI!
