### ISSUE TITLE
[bug] Results paging bug for collections with type None items

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#356]
To reproduce:
- go to https://calisphere-stage.cdlib.org/collections/469/
- hit the forward arrow button to go to page 2

This results in no items displayed and "1 item found in this collection of 66 items" heading.

url: https://calisphere-stage.cdlib.org/collections/469/?q=&sort=a&type_ss=&start=24

This is because we are currently including records with `type_ss=None` in our faceting query. The "next page" URL includes the `type_ss` facet, which defaults to no value, and there is only one record with type None in this collection.

**Comment by amywieliczka** [comment]
This should be resolved with https://github.com/ucldc/public_interface/pull/351, but let's check once that's merged in.

**Comment by christinklez** [comment]
Both of these collections (type not supplied & date not supplied) look good on -stage! Also tested out with viewing 24 items & 48 items. Thanks!
