### ISSUE TITLE
[bug?] A previously existing Calisphere record (with an ARK) that has since been removed intentionally results as a 500 page on -stage

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#377]
This record is on production: https://calisphere.org/item/ark:/20775/bb79573069/
UCSD requested that we remove the object -- they have also removed this from their DAMS.

Since then, we have reharvested the collection directly from their DAMS; the collection looks good on -stage (with minus one record, as expected).
However, I tried out this URL just to confirm that the record was gone: https://calisphere-stage.cdlib.org/item/ark:/20775/bb79573069/ -- it results in a 500 error page.

Expected behavior: I would expect to get our classic 404 bowling ball page.

**Comment by amywieliczka** [comment]
Closed by https://github.com/ucldc/public_interface/pull/376

**Comment by amywieliczka** [comment]
@christinklez - Closing because I'm now seeing a 404!
