### ISSUE TITLE
[to do] Enable stemming for OpenSearch queries (i.e., `cats` and `cat` should produce similar results)

### ISSUE THREAD

**Issue by christinklez** [ucldc/public_interface#382]
Needs tweaking? Rikolti seems to be strict about pluralization?

"cats"" https://calisphere.org/UCI/items/?rq=cats - 16 results

"cats"" https://calisphere-stage.cdlib.org/UCI/items/?rq=cats - 2 results

"cat"" https://calisphere-stage.cdlib.org/UCI/items/?rq=cat - 16 results

Also, this record only shows up for "cats" but not "cat": https://calisphere-stage.cdlib.org/item/ark:/13030/hb4r29n9hz/

**Comment by amywieliczka** [comment]
I'm adding `analyzer: english` at query-time, which may make queries slower. We could also re-index with this analyzer on all our text fields to incur the compute cost at index time.
